/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as EdicaoImpressaRouteImport } from './routes/edicao-impressa'
import { Route as ContactosUteisRouteImport } from './routes/contactos-uteis'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ConcursosPublicosRouteImport } from './routes/concursos-publicos'
import { Route as ArtigosRouteImport } from './routes/artigos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtigosCategoryRouteImport } from './routes/artigos.$category'

const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const EdicaoImpressaRoute = EdicaoImpressaRouteImport.update({
  id: '/edicao-impressa',
  path: '/edicao-impressa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosUteisRoute = ContactosUteisRouteImport.update({
  id: '/contactos-uteis',
  path: '/contactos-uteis',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcursosPublicosRoute = ConcursosPublicosRouteImport.update({
  id: '/concursos-publicos',
  path: '/concursos-publicos',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosRoute = ArtigosRouteImport.update({
  id: '/artigos',
  path: '/artigos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtigosCategoryRoute = ArtigosCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ArtigosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRouteWithChildren
  '/concursos-publicos': typeof ConcursosPublicosRoute
  '/contactos': typeof ContactosRoute
  '/contactos-uteis': typeof ContactosUteisRoute
  '/edicao-impressa': typeof EdicaoImpressaRoute
  '/eventos': typeof EventosRoute
  '/sobre-nos': typeof SobreNosRoute
  '/artigos/$category': typeof ArtigosCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRouteWithChildren
  '/concursos-publicos': typeof ConcursosPublicosRoute
  '/contactos': typeof ContactosRoute
  '/contactos-uteis': typeof ContactosUteisRoute
  '/edicao-impressa': typeof EdicaoImpressaRoute
  '/eventos': typeof EventosRoute
  '/sobre-nos': typeof SobreNosRoute
  '/artigos/$category': typeof ArtigosCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artigos': typeof ArtigosRouteWithChildren
  '/concursos-publicos': typeof ConcursosPublicosRoute
  '/contactos': typeof ContactosRoute
  '/contactos-uteis': typeof ContactosUteisRoute
  '/edicao-impressa': typeof EdicaoImpressaRoute
  '/eventos': typeof EventosRoute
  '/sobre-nos': typeof SobreNosRoute
  '/artigos/$category': typeof ArtigosCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artigos'
    | '/concursos-publicos'
    | '/contactos'
    | '/contactos-uteis'
    | '/edicao-impressa'
    | '/eventos'
    | '/sobre-nos'
    | '/artigos/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artigos'
    | '/concursos-publicos'
    | '/contactos'
    | '/contactos-uteis'
    | '/edicao-impressa'
    | '/eventos'
    | '/sobre-nos'
    | '/artigos/$category'
  id:
    | '__root__'
    | '/'
    | '/artigos'
    | '/concursos-publicos'
    | '/contactos'
    | '/contactos-uteis'
    | '/edicao-impressa'
    | '/eventos'
    | '/sobre-nos'
    | '/artigos/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtigosRoute: typeof ArtigosRouteWithChildren
  ConcursosPublicosRoute: typeof ConcursosPublicosRoute
  ContactosRoute: typeof ContactosRoute
  ContactosUteisRoute: typeof ContactosUteisRoute
  EdicaoImpressaRoute: typeof EdicaoImpressaRoute
  EventosRoute: typeof EventosRoute
  SobreNosRoute: typeof SobreNosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edicao-impressa': {
      id: '/edicao-impressa'
      path: '/edicao-impressa'
      fullPath: '/edicao-impressa'
      preLoaderRoute: typeof EdicaoImpressaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos-uteis': {
      id: '/contactos-uteis'
      path: '/contactos-uteis'
      fullPath: '/contactos-uteis'
      preLoaderRoute: typeof ContactosUteisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concursos-publicos': {
      id: '/concursos-publicos'
      path: '/concursos-publicos'
      fullPath: '/concursos-publicos'
      preLoaderRoute: typeof ConcursosPublicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos': {
      id: '/artigos'
      path: '/artigos'
      fullPath: '/artigos'
      preLoaderRoute: typeof ArtigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artigos/$category': {
      id: '/artigos/$category'
      path: '/$category'
      fullPath: '/artigos/$category'
      preLoaderRoute: typeof ArtigosCategoryRouteImport
      parentRoute: typeof ArtigosRoute
    }
  }
}

interface ArtigosRouteChildren {
  ArtigosCategoryRoute: typeof ArtigosCategoryRoute
}

const ArtigosRouteChildren: ArtigosRouteChildren = {
  ArtigosCategoryRoute: ArtigosCategoryRoute,
}

const ArtigosRouteWithChildren =
  ArtigosRoute._addFileChildren(ArtigosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtigosRoute: ArtigosRouteWithChildren,
  ConcursosPublicosRoute: ConcursosPublicosRoute,
  ContactosRoute: ContactosRoute,
  ContactosUteisRoute: ContactosUteisRoute,
  EdicaoImpressaRoute: EdicaoImpressaRoute,
  EventosRoute: EventosRoute,
  SobreNosRoute: SobreNosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
